### ISSUE TITLE
Error installing pocolm through JupyterLab

### ISSUE THREAD

**Issue by abdallah1989203** [danpovey/pocolm#105]
i am trying to use pocolm but i have an error with pocolm/scripts/check_dependencies.sh. 
there seems to be an error when I install python-numpy even though the package is already there.

![Bildschirmfoto 2022-01-25 um 19 39 17](https://user-images.githubusercontent.com/49979501/151038586-46f38c61-666f-4d99-976a-520baec8decf.png)

**Comment by danpovey** [comment]
It seems there is another PR
https://github.com/danpovey/pocolm/pull/95
that needs to be tested and merged.  That moves everything over to python3, but there are some locale-related issues that we need to solve.  You could perhaps help us test that, but we needed to make a change to the python scripts, by adding something at the top and re-testing.

**Comment by abdallah1989203** [comment]
it must restart the core again after this step
Done!
