### ISSUE TITLE
new bug

### ISSUE THREAD

**Issue by vince62s** [danpovey/pocolm#23]
I am running the "basic" swbd script on a new corpus with vocab size 200000.
Just after the start of pruning it fails as below:

pre-arpa-to-arpa: success
format_arpa_lm.py: succeeded formatting ARPA lm from data/lm_200k_3
get_data_prob.py: log-prob of data/text/dev.txt given model data/lm_200k_3 was -4.52184459877 per word [perplexity = 92.0051541426] over 203972.0 words.
histories-to-null-counts: processed 199693 LM states, with 16926037 individual n-grams.
float-counts-to-float-stats 200000 data/lm_200k_3_prune1.0/work/iter0/stats.1 data/lm_200k_3_prune1.0/work/iter0/stats.2 data/lm_200k_3_prune1.0/work/iter0/stats.3 <data/lm_200k_3_prune1.0/work/iter0/float.all
float-counts-to-float-stats: float-counts-to-float-stats.cc:254: void pocolm::FloatStatsGenerator::FinalizeLmState(int32): Assertion `src_count > -1.0e-04 \* old_total' failed.

**Comment by danpovey** [comment]
Thanks-- I just changed the error to a warning [was about excessive
roundoff].

**Comment by vince62s** [comment]
pre-arpa-to-arpa: success
format_arpa_lm.py: succeeded formatting ARPA lm from data/lm_200k_4
get_data_prob.py: log-prob of data/text/dev.txt given model data/lm_200k_4 was -4.34160109574 per word [perplexity = 76.8304538253] over 203972.0 words.
histories-to-null-counts: processed 3642513 LM states, with 17294290 individual n-grams.
float-counts-to-float-stats 200000 data/lm_200k_4_prune1.0/work/iter0/stats.1 data/lm_200k_4_prune1.0/work/iter0/stats.2 data/lm_200k_4_prune1.0/work/iter0/stats.3 data/lm_200k_4_prune1.0/work/iter0/stats.4 <data/lm_200k_4_prune1.0/work/iter0/float.all
float-counts-to-float-stats: float-counts-to-float-stats.cc:305: void pocolm::FloatStatsGenerator::DoProcessingForLmState(int32): Assertion `proportion_remaining > -1.0e-3' failed.
moses@sge-master:/netshr/pocolm/egs/news2014$

**Comment by danpovey** [comment]
Just pushed a fix as  1dd2e7f

**Comment by danpovey** [comment]
Please let me know what warnings that program prints now- I changed the
assert to a warning.

**Comment by vince62s** [comment]
float-counts-to-pre-arpa: output [ 3351297 3887363 4783662 ] n-grams
float-counts-to-pre-arpa: output [ 3374709 3747784 4730403 ] n-grams
float-counts-to-pre-arpa: output [ 3399539 3999331 4993155 ] n-grams
float-counts-to-pre-arpa: output [ 3415939 4604757 5777222 ] n-grams
float-counts-to-pre-arpa: output [ 200000 3343832 3765992 5100998 ] n-grams
pre-arpa-to-arpa: success
format_arpa_lm.py: succeeded formatting ARPA lm from data/lm_200k_4
get_data_prob.py: log-prob of data/text/dev.txt given model data/lm_200k_4 was -4.34160109574 per word [perplexity = 76.8304538253] over 203972.0 words.
warning: in float-counts,0.315192 != 0.390464
warning: in float-counts,0.287675 != 0.557137
merge-float-counts: lm-state.cc:291: void pocolm::FloatLmState::Check() const: Assertion `discount >= 0.0' failed.
moses@sge-master:/netshr/pocolm/egs/news2014$

**Comment by vince62s** [comment]
I posted the above in haste sorry but did you see the 2 warnings and then the error after ? occuring at order 4 step.

**Comment by danpovey** [comment]
What command did you run to get this error, and on what kind of setup?

**Comment by vince62s** [comment]
still the same as yesterday, same run.sh as swbd, but with a big corpus. order 3 step runs fine, order 4 breaks at the step above.

**Comment by danpovey** [comment]
OK; can you show me a bit more context of the error and maybe try to run
the command that immediately produced with --verbose if it's supported by
that script?
Dan

**Comment by vince62s** [comment]
it has to be at the prume_lm_dir.py step in the run.sh, I am trying to run it with a pruning threshold of 4 instead of 1. does this script support --verbose ?

**Comment by vince62s** [comment]
same error. I don't know where to add the --verbose , don't think it's supported in prune_lm_dir.py
just one more thing about the context, it's with the min-count=2 during the counting steps.

**Comment by danpovey** [comment]
It doesn't currently support --verbose.
OK.  Ke and Zhouyang, please try running the tedlium setup without taking a
subset of data (in fact, it would be good if you check in these changes so
that the tedlium setup does not use a subset).  And prune with a large
threshold.  Maybe you'll be able to replicate this problem.

Dan

**Comment by vince62s** [comment]
in the meantime I'll run order 5 to see if the issue is the same.

**Comment by danpovey** [comment]
BTW, what min-count are you using?

**Comment by vince62s** [comment]
just one more thing about the context, it's with the min-count=2 during the counting steps.

**Comment by vince62s** [comment]
order 5 running now, will keep you posted "tomorrow" ...

**Comment by danpovey** [comment]
Please update your scripts and re-run the order 4 pruning with
--verbose=true, it may tell us more more about what went wrong.
I'm interested not only in the logs that failed, but also in the others log
files in the iteration that failed, and the previous iteration.  They are
short so you can just cat them.

Dan

**Comment by vince62s** [comment]
[prune4.0-step.tar.gz](https://github.com/danpovey/pocolm/files/340768/prune4.0-step.tar.gz)

should be what you need.

**Comment by danpovey** [comment]
Thanks.  I believe I have fixed this.  Bear in mind that the real error was much earlier, in dumping counts.  So you may have to remove the old counts as well as recompile.
