### ISSUE TITLE
get_counts.py issue

### ISSUE THREAD

**Issue by vince62s** [danpovey/pocolm#24]
here ...

 set -o pipefail; gunzip -c data/int_200k/dev.txt.gz | get-text-counts 3 | sort | uniq -c | get-int-counts /dev/null data/counts_200k_3/int.dev.2 data/counts_200k_3/int.dev.3
 running at Tue Jun 28 17:00:00 2016
get-text-counts: processed 10000 lines, with (on average) 21.3972 words per line.
get-int-counts: lm-state.cc:143: void pocolm::IntLmState::Check() const: Assertion `counts[i].first < counts[i+1].first' failed.
uniq: write error: Broken pipe
/bin/sh: line 1: 48048 Done                    gunzip -c data/int_200k/dev.txt.gz
     48049                       | get-text-counts 3
     48050                       | sort
     48051 Done(1)                 | uniq -c
     48052 Aborted                 (core dumped) | get-int-counts /dev/null data/counts_200k_3/int.dev.2 data/counts_200k_3/int.dev.3
 exited with return code 0 after 2.4 seconds

**Comment by danpovey** [comment]
A locale problem, most likely.
I just pushed a change, see if it helps.

**Comment by vince62s** [comment]
validate_vocab.py: validated file data/int_200k/words.txt with 200000 entries.
get_counts.py: command bash -c 'set -o pipefail; LC_ALL=C; gunzip -c data/int_200k/dev.txt.gz | get-text-counts 3 | sort | uniq -c | get-int-counts /dev/null data/counts_200k_3/int.dev.2 data/counts_200k_3/int.dev.3' exited with status 134, output is in data/counts_200k_3/log/get_counts.dev.log

here is the log

 bash -c 'set -o pipefail; LC_ALL=C; gunzip -c data/int_200k/dev.txt.gz | get-text-counts 3 | sort | uniq -c | get-int-counts /dev/null data/counts_200k_3/int.dev.2 data/counts_200k_3/int.dev.3'
 running at Tue Jun 28 20:18:09 2016
get-text-counts: processed 10000 lines, with (on average) 21.3972 words per line.
get-int-counts: lm-state.cc:143: void pocolm::IntLmState::Check() const: Assertion `counts[i].first < counts[i+1].first' failed.
uniq: write error: Broken pipe
bash: line 1: 50112 Done                    gunzip -c data/int_200k/dev.txt.gz
     50113                       | get-text-counts 3
     50114                       | sort
     50115 Exit 1                  | uniq -c
     50116 Aborted                 (core dumped) | get-int-counts /dev/null data/counts_200k_3/int.dev.2 data/counts_200k_3/int.dev.3
 exited with return code 0 after 2.4 seconds

**Comment by danpovey** [comment]
Can you try changing it to
'export LC_ALL=C' and see if that fixes the issue?
Dan

**Comment by vince62s** [comment]
seems OK, changed it in 2 places

**Comment by danpovey** [comment]
Cool, thanks.  Could you please submit a PR with that?

**Comment by vince62s** [comment]
yes but I'll let it run till the end to check the other fix is fine.
btw, my goal is to compare a pocolm from a non filtered corpus with the srilm maxent.
but I am having memory issues with srilm maxent and big corpus ....

**Comment by danpovey** [comment]
Hm.  You may have to run the maxent comparison on a smaller dataset.
Even if you solved the memory problem, I don't know that training the
maxent model would be that fast.
Dan

**Comment by vince62s** [comment]
I had done the maxent test with the tedlium corpus (results in the srilm_baseline_tedlium.sh) but since it is entropy filtered maybe the comparison was not relevant. I would like to see in a bigger scale. maxent was quite fast on tedlium but my new corpus is twice as big.

**Comment by danpovey** [comment]
OK.  It looks like the Kneser-Ney->maxent change, at 107.7->105.9, is a
similar magnitude to the change from Kneser-Ney -> pocolm, so worthwhile
comparing the two.

I notice that in your TEDLIUM examples you seem to be using a subset of
data.
I think the toolkit might be fast enough now that it would be worthwhile
using the full data set for all the experiments.

Dan

**Comment by vince62s** [comment]
I had posted this also (for unpruned):
"FYI maxent is in between poco and kn. For order 4: 176.91 / 179.83 / 185.99"
Now after Remi's comment I am thinking that from a not-filtered corpus, maxent and poco could be closer. I'll  try to change my server and install the maxent patch on a 128GB ram server.
