### ISSUE TITLE
multiple sources / interpolation

### ISSUE THREAD

**Issue by vince62s** [danpovey/pocolm#26]
Dan,
Question on multiple sources.
I guess it does not just concatenate the various sources.
Is there a linear interpolation or can we put some weights to one source vs another ?
how does it work right now ?

**Comment by danpovey** [comment]
It estimates interpolation weights as part of the LM estimation itself.
That's why you have to provide the sources separately.

**Comment by vince62s** [comment]
but what if the sources are very different in size. would that require kind of a way to overweight the smaller source ?

**Comment by danpovey** [comment]
It's all done automatically in a way that maximizes the probability of dev
data.
