### ISSUE TITLE
erros with higher number in vocab size

### ISSUE THREAD

**Issue by vince62s** [danpovey/pocolm#6]
I ran two experiments, one with a big corpus and then tried also with swbd.
Just changing the vocab size to 150000 in the run.sh script throws this error below:

validate_vocab.py: validated file data/vocab_20k.txt with 32151 entries.
validate_vocab.py: validated file data/int_20k/words.txt with 32151 entries.
# gunzip -c data/int_20k/1.txt.gz | get-text-counts 3 | sort | uniq -c | get-int-counts /dev/null data/counts_20k_3/int.1.2 data/counts_20k_3/int.1.3

get-text-counts: processed 254334 lines, with (on average) 13.8486 words per line.get-int-counts: lm-state.cc:116: void pocolm::IntLmState::Check() const: Assertion `counts[i].first < counts[i+1].first' failed.
/netshr/pocolm/scripts/get_counts.sh: line 74: 26311 Done                    gunzip -c $int/$n.txt.gz
     26312                       | get-text-counts $ngram_order
     26313 Broken pipe             | sort
     26314 Broken pipe             | uniq -c
     26315 Aborted                 (core dumped) | get-int-counts $args
/netshr/pocolm/scripts/get_counts.sh: error detected; check the logs in data/counts_20k_3/log
moses@sge-master:/netshr/pocolm/egs/swbd$ 

With a bigger corpus another one :
Created 2 .counts files in data/word_counts
counts_to_vocab.py: severe warning: end-of-sentence symbol </s> appears in the text. It will be replaced by <unk> during data preparation.
counts_to_vocab.py: you specified --num-words=150000 so limiting the vocabulary from 834779 to 150000 words based on count.
counts_to_vocab.py: created vocabulary with 150000 entries
/netshr/pocolm/scripts/text_to_int.py
validate_vocab.py: validated file data/vocab_150k.txt with 150000 entries.
validate_vocab.py: validated file data/int_150k/words.txt with 150000 entries.

gzip: data/int_150k/dev.txt.gz: unexpected end of file
Traceback (most recent call last):
  File "/netshr/pocolm/scripts/validate_int_dir.py", line 114, in <module>
    args.int_dir, name))
IndexError: tuple index out of range

surprisingly, if running run.sh again on this one, it continues fine.

**Comment by danpovey** [comment]
That's odd and I can't replicate it here. What is your locale? E.g.

printenv | grep -E 'LO?C'

will show the relevant variables.
Dan

**Comment by vince62s** [comment]
this command gives nothing, but (on ubuntu 14) when I type locale, here is the result:
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Comment by danpovey** [comment]
Do "git pull" to update the script, I do "export LC_ALL=C" in that script.
It might fix the problem.
Dan

**Comment by vince62s** [comment]
okay it fixed the first issue, not the second one.

**Comment by danpovey** [comment]
Not sure what you  mean by 1st and second issue.

**Comment by vince62s** [comment]
Created 2 .counts files in data/word_counts
counts_to_vocab.py: severe warning: end-of-sentence symbol appears in the text. It will be replaced by during data preparation.
counts_to_vocab.py: you specified --num-words=150000 so limiting the vocabulary from 834779 to 150000 words based on count.
counts_to_vocab.py: created vocabulary with 150000 entries
/netshr/pocolm/scripts/text_to_int.py
validate_vocab.py: validated file data/vocab_150k.txt with 150000 entries.
validate_vocab.py: validated file data/int_150k/words.txt with 150000 entries.

**gzip: data/int_150k/dev.txt.gz: unexpected end of file
Traceback (most recent call last):
File "/netshr/pocolm/scripts/validate_int_dir.py", line 114, in
args.int_dir, name))
IndexError: tuple index out of range**

surprisingly, if running run.sh again on this one, it continues fine.

**Comment by danpovey** [comment]
> Created 2 .counts files in data/word_counts
> counts_to_vocab.py: severe warning: end-of-sentence symbol appears in the
> text. It will be replaced by during data preparation.

Are you sure you removed the EOS symbol from all of the text?  It looks to
me like you didn't.

> counts_to_vocab.py: you specified --num-words=150000 so limiting the
> vocabulary from 834779 to 150000 words based on count.
> counts_to_vocab.py: created vocabulary with 150000 entries
> /netshr/pocolm/scripts/text_to_int.py
> validate_vocab.py: validated file data/vocab_150k.txt with 150000 entries.
> validate_vocab.py: validated file data/int_150k/words.txt with 150000
> entries.
> 
> _gzip: data/int_150k/dev.txt.gz: unexpected end of file Traceback (most
> recent call last): File "/netshr/pocolm/scripts/validate_int_dir.py", line
> 114, in args.int_dir, name)) IndexError: tuple index out of range_

I just fixed a bug in the python script but there is still a problem with
the file data/int_150k/dev.txt.gz.  It might be empty or truncated.  Is
data/text/dev.txt (or data/text/dev.txt.gz) empty?

Dan

_gzip: data/int_150k/dev.txt.gz: unexpected end of fileTraceback (most
recent call last):File "/netshr/pocolm/scripts/validate_int_dir.py", line
114, inargs.int_dir, name))_
_IndexError: tuple index out of range_

**Comment by danpovey** [comment]
Also if you could show me the commands that you are running when you get
this output it would be helpful.  Otherwise I am having to guess what you
might be trying to do.

**Comment by vince62s** [comment]
it's annoying, I am having hard time to replicate 100%. The weird thing is that when this error pops, dev.txt or dev.txt.gz are not empty at all. I am not running different commands other than changing the vocab size and adjusting the names to match the vocab size. And each time it happens, if ./run.sh again it will work fine. Looks like an environment issue.
I'll try again various tests to make this consistent.

Also the EOS warning was on another corpus, but it kept doing it also on cantab without that warning.

**Comment by vince62s** [comment]
Dan, I think I found what's happening. I checked the time of the 1.txt.gz file. it is > to the time of the counts file. Which means I think the gzip process finishes after the next script already tries to unzip. This happens with bigger corpus (> 1GB) and might be the reason why you never face it.
Or can I be wrong and it's all sequential ?

**Comment by danpovey** [comment]
Thanks for finding this-- I think I found a couple of specific errors in
scripts, where they neglected to 'wait' for background processes.  I pushed
a fix.  See if it clears up now.
Dan

**Comment by vince62s** [comment]
fixed. Thanks.
