### ISSUE TITLE
Timing / performance

### ISSUE THREAD

**Issue by vince62s** [danpovey/pocolm#8]
I re-ran one order make this clearer (order 5 only): 3 hours  34 minutes.
10 splits, ratio 20.
Second call to optimize parameters runs 6 iterations (from 0 to 5) and each one lasts exactly 20 minutes. During each, at times, only one process discount-counts is running.
So just this step is 2 hours.
Last step to build the arpa run 48 minutes to build a 2.7GB gz file.

For the record, yes swbd runs in 11 minutes on my machine too.

**Comment by vince62s** [comment]
Given a certain corpus, when we change the dev set, can it impact the processing time, ie could there be more iterations in some circumstances ? (it's been running for more than 12 hours now, for the same corpus that used to run in about 10.5/11 hours)

**Comment by danpovey** [comment]
It might- or maybe the machine is busy with something else.

**Comment by vince62s** [comment]
finished. almost 15 hours.... machine was fully dedicated (and not a bad one)
anyway, it's done.

**Comment by danpovey** [comment]
At some point I added pruning to that script.  So it may not be running the
same things as before.
I'm about to make further changes which may make it faster.
Dan
